Repository infinispan/infinispan-operator, pull requests merged in 2021-04, with the labels that each got.

#919 ISPN-12853 grafana dashboard docs
  documentation/asciidoc/stories/assembly_logging.adoc
  documentation/asciidoc/stories/assembly_monitoring.adoc
  documentation/asciidoc/stories/assembly_setting_up_prometheus.adoc
  documentation/asciidoc/titles/stories.adoc
  documentation/asciidoc/topics/attributes/links.adoc
  documentation/asciidoc/topics/cmd_examples/get_operator_credentials.adoc
  documentation/asciidoc/topics/cmd_examples/oc_get_secret_creds_jp.adoc
  documentation/asciidoc/topics/cmd_examples/oc_get_secret_operator_creds.adoc
  documentation/asciidoc/topics/proc_configuring_grafana_dashboards.adoc
  documentation/asciidoc/topics/proc_creating_grafana_datasources.adoc
  documentation/asciidoc/topics/proc_creating_service_monitor.adoc
  documentation/asciidoc/topics/proc_installing_grafana_operator.adoc
  documentation/asciidoc/topics/ref_default_credentials.adoc
  documentation/asciidoc/topics/yaml/basic_auth.yaml
  documentation/asciidoc/topics/yaml/grafana_datasource.yaml
  documentation/asciidoc/topics/yaml/infinispan_operator_config.yaml
  documentation/asciidoc/topics/yaml/prometheus_service_account.yaml
  documentation/asciidoc/topics/yaml/prometheus_service_monitor.yaml
  documentation/asciidoc/topics/yaml/service_monitor.yaml
Labels: documentation, downstream

#977 ISPN-12916 [Operator] Grafana is Querying on stat that exists for def…
  pkg/controller/infinispan/resources/operatorconfig/monitoring_constants.go
Labels: bug

#982 Remove path field from OLM entry for Backup and Restore
  deploy/olm-catalog/infinispan-operator.clusterserviceversion.yaml
Labels: documentation

#964 Cloud Event integration #962
  deploy/crds/infinispan.org_infinispans_crd.yaml
  deploy/operator-install.yaml
  pkg/apis/infinispan/v1/infinispan_types.go
  pkg/apis/infinispan/v1/zz_generated.deepcopy.go
  pkg/controller/infinispan/resources/config/config_controller.go
  pkg/infinispan/configuration/configuration.go
Labels: documentation

#988 ISPN-12926 [Operator] Grafana dashboard does not differentiate betwee…
  pkg/controller/infinispan/resources/operatorconfig/monitoring_constants.go
Labels: bug

#996 cloud event docs #962
  documentation/asciidoc/stories/assembly_cache_cr.adoc
  documentation/asciidoc/stories/assembly_eventing.adoc
  documentation/asciidoc/titles/stories.adoc
  documentation/asciidoc/topics/con_cache_cr.adoc
  documentation/asciidoc/topics/con_cloud_events.adoc
  documentation/asciidoc/topics/json/cloud_events.json
  documentation/asciidoc/topics/proc_enabling_cloud_events.adoc
  documentation/asciidoc/topics/yaml/cloud_events.yaml
Labels: documentation, downstream
